export default {

    POST_MPIN_EMPLOYEE_REQUEST:'POST_MPIN_EMPLOYEE_REQUEST',
    POST_MPIN_EMPLOYEE_SUCCESS:'POST_MPIN_EMPLOYEE_SUCCESS',
    POST_MPIN_EMPLOYEE_FAILURE:'POST_MPIN_EMPLOYEE_FAILURE',
    POST_MPIN_EMPLOYEE_FAILURE_INVALID:'POST_MPIN_EMPLOYEE_FAILURE_INVALID',
    
    POST_LOGIN_EMPLOYEE_REQUEST:'POST_LOGIN_EMPLOYEE_REQUEST',
    POST_LOGIN_EMPLOYEE_SUCCESS:'POSTL_LOGIN_EMPLOYEE_SUCCESS',
    POST_LOGIN_EMPLOYEE_FAILURE:'POST_LOGIN_EMPLOYEE_FAILURE',
    POST_LOGIN_EMPLOYEE_FAILURE_INVALID:'POST_LOGIN_EMPLOYEE_FAILURE_INVALID', 

    POST_FORGOT_PASSWORD_REQUEST:'POST_FORGOT_PASSWORD_REQUEST',
    POST_FORGOT_PASSWORD_SUCCESS:'POSTL_FORGOT_PASSWORD_SUCCESS',
    POST_FORGOT_PASSWORD_FAILURE:'POST_FORGOT_PASSWORD_FAILURE',
    POST_FORGOT_PASSWORD_FAILURE_INVALID:'POST_FORGOT_PASSWORD_FAILURE_INVALID', 

    POST_LIST_LINE_RUN_REQUEST:'POST_LIST_LINE_RUN_REQUEST',
    POST_LIST_LINE_RUN_SUCCESS:'POST_LIST_LINE_RUN_SUCCESS',
    POST_LIST_LINE_RUN_FAILURE:'POST_LIST_LINE_RUN_FAILURE',
    POST_LIST_LINE_RUN_FAILURE_INVALID:'POST_LIST_LINE_RUN_FAILURE_INVALID',

    POST_INTEGRATION_START_LINE_RUN_REQUEST:'POST_INTEGRATION_START_LINE_RUN_REQUEST',
    POST_INTEGRATION_START_LINE_RUN_SUCCESS:'POST_INTEGRATION_START_LINE_RUN_SUCCESS',
    POST_INTEGRATION_START_LINE_RUN_FAILURE:'POST_INTEGRATION_START_LINE_RUN_FAILURE',
    POST_INTEGRATION_START_LINE_RUN_FAILURE_INVALID:'POST_INTEGRATION_START_LINE_RUN_FAILURE_INVALID',


    POST_INTEGRATION_GETEDIT_LINE_RUN_REQUEST:'POST_INTEGRATION_GETEDIT_LINE_RUN_REQUEST',
    POST_INTEGRATION_GETEDIT_LINE_RUN_SUCCESS:'POST_INTEGRATION_GETEDIT_LINE_RUN_SUCCESS',
    POST_INTEGRATION_GETEDIT_LINE_RUN_FAILURE:'POST_INTEGRATION_GETEDIT_LINE_RUN_FAILURE',
    POST_INTEGRATION_GETEDIT_LINE_RUN_FAILURE_INVALID:'POST_INTEGRATION_GETEDIT_LINE_RUN_FAILURE_INVALID',

    POST_INTEGRATION_ADDEDIT_LINE_RUN_REQUEST:'POST_INTEGRATION_ADDEDIT_LINE_RUN_REQUEST',
    POST_INTEGRATION_ADDEDIT_LINE_RUN_SUCCESS:'POST_INTEGRATION_ADDEDIT_LINE_RUN_SUCCESS',
    POST_INTEGRATION_ADDEDIT_LINE_RUN_FAILURE:'POST_INTEGRATION_ADDEDIT_LINE_RUN_FAILURE',
    POST_INTEGRATION_ADDEDIT_LINE_RUN_FAILURE_INVALID:'POST_INTEGRATION_ADDEDIT_LINE_RUN_FAILURE_INVALID',

    POST_INTEGRATION_VIEW_LINE_RUN_REQUEST:'POST_INTEGRATION_VIEW_LINE_RUN_REQUEST',
    POST_INTEGRATION_VIEW_LINE_RUN_SUCCESS:'POST_INTEGRATION_VIEW_LINE_RUN_SUCCESS',
    POST_INTEGRATION_VIEW_LINE_RUN_FAILURE:'POST_INTEGRATION_VIEW_LINE_RUN_FAILURE',
    POST_INTEGRATION_VIEW_LINE_RUN_FAILURE_INVALID:'POST_INTEGRATION_VIEW_LINE_RUN_FAILURE_INVALID',

    POST_INTEGRATION_PLACEMENTS_FOR_LINE_RUN_REQUEST:'POST_INTEGRATION_PLACEMENTS_FOR_LINE_RUN_REQUEST',
    POST_INTEGRATION_PLACEMENTS_FOR_LINE_RUN_SUCCESS:'POST_INTEGRATION_PLACEMENTS_FOR_LINE_RUN_SUCCESS',
    POST_INTEGRATION_PLACEMENTS_FOR_LINE_RUN_FAILURE:'POST_INTEGRATION_PLACEMENTS_FOR_LINE_RUN_FAILURE',
    POST_INTEGRATION_PLACEMENTS_FOR_LINE_RUN_FAILURE_INVALID:'POST_INTEGRATION_PLACEMENTS_FOR_LINE_RUN_FAILURE_INVALID',

    POST_INTEGRATION_LOAD_DATA_FOR_DATAENTRY_REQUEST:'POST_INTEGRATION_LOAD_DATA_FOR_DATAENTRY_REQUEST',
    POST_INTEGRATION_LOAD_DATA_FOR_DATAENTRY_SUCCESS:'POST_INTEGRATION_LOAD_DATA_FOR_DATAENTRY_SUCCESS',
    POST_INTEGRATION_LOAD_DATA_FOR_DATAENTRY_FAILURE:'POST_INTEGRATION_LOAD_DATA_FOR_DATAENTRY_FAILURE',
    POST_INTEGRATION_LOAD_DATA_FOR_DATAENTRY_FAILURE_INVALID:'POST_INTEGRATION_LOAD_DATA_FOR_DATAENTRY_FAILURE_INVALID',

    POST_INTEGRATION_LOAD_DATA_FOR_BODYWYTENTRY_REQUEST:'POST_INTEGRATION_LOAD_DATA_FOR_BODYWYTENTRY_REQUEST',
    POST_INTEGRATION_LOAD_DATA_FOR_BODYWYTENTRY_SUCCESS:'POST_INTEGRATION_LOAD_DATA_FOR_BODYWYTENTRY_SUCCESS',
    POST_INTEGRATION_LOAD_DATA_FOR_BODYWYTENTRY_FAILURE:'POST_INTEGRATION_LOAD_DATA_FOR_BODYWYTENTRY_FAILURE',
    POST_INTEGRATION_LOAD_DATA_FOR_BODYWYTENTRY_FAILURE_INVALID:'POST_INTEGRATION_LOAD_DATA_FOR_BODYWYTENTRY_FAILURE_INVALID',

    POST_INTEGRATION_BODY_WEIGHT_ENTRY_REQUEST:'POST_INTEGRATION_BODY_WEIGHT_ENTRY_REQUEST',
    POST_INTEGRATION_BODY_WEIGHT_ENTRY_SUCCESS:'POST_INTEGRATION_BODY_WEIGHT_ENTRY_SUCCESS',
    POST_INTEGRATION_BODY_WEIGHT_ENTRY_FAILURE:'POST_INTEGRATION_BODY_WEIGHT_ENTRY_FAILURE',
    POST_INTEGRATION_BODY_WEIGHT_ENTRY_FAILURE_INVALID:'POST_INTEGRATION_BODY_WEIGHT_ENTRY_FAILURE_INVALID',

    POST_INTEGRATION_ADJUSTMENTENTRY_REQUEST:'POST_INTEGRATION_ADJUSTMENTENTRY_REQUEST',
    POST_INTEGRATION_ADJUSTMENTENTRY_SUCCESS:'POST_INTEGRATION_ADJUSTMENTENTRY_SUCCESS',
    POST_INTEGRATION_ADJUSTMENTENTRY_FAILURE:'POST_INTEGRATION_ADJUSTMENTENTRY_FAILURE',
    POST_INTEGRATION_ADJUSTMENTENTRY_FAILURE_INVALID:'POST_INTEGRATION_ADJUSTMENTENTRY_FAILURE_INVALID',

    POST_INTEGRATION_DATAENTRY_REQUEST:'POST_INTEGRATION_DATAENTRY_REQUEST',
    POST_INTEGRATION_DATAENTRY_SUCCESS:'POST_INTEGRATION_DATAENTRY_SUCCESS',
    POST_INTEGRATION_DATAENTRY_FAILURE:'POST_INTEGRATION_DATAENTRY_FAILURE',
    POST_INTEGRATION_DATAENTRY_FAILURE_INVALID:'POST_INTEGRATION_DATAENTRY_FAILURE_INVALID',

    POST_MASTERS_LINE_LIST_REQUEST:'POST_MASTERS_LINE_LIST_REQUEST',
    POST_MASTERS_LINE_LIST_SUCCESS:'POST_MASTERS_LINE_LIST_SUCCESS',
    POST_MASTERS_LINE_LIST_FAILURE:'POST_MASTERS_LINE_LIST_FAILURE',
    POST_MASTERS_LINE_LIST_FAILURE_INVALID:'POST_MASTERS_LINE_LIST_FAILURE_INVALID',

    POST_MASTERS_LINE_RUN_PURPOSE_REQUEST:'POST_MASTERS_LINE_RUN_PURPOSE_REQUEST',
    POST_MASTERS_LINE_RUN_PURPOSE_SUCCESS:'POST_MASTERS_LINE_RUN_PURPOSE_SUCCESS',
    POST_MASTERS_LINE_RUN_PURPOSE_FAILURE:'POST_MASTERS_LINE_RUN_PURPOSE_FAILURE',
    POST_MASTERS_LINE_RUN_PURPOSE_FAILURE_INVALID:'POST_MASTERS_LINE_RUN_PURPOSE_FAILURE_INVALID',

    POST_USER_USER_LIST_REQUEST:'POST_USER_USER_LIST_REQUEST',
    POST_USER_USER_LIST_SUCCESS:'POST_USER_USER_LIST_SUCCESS',
    POST_USER_USER_LIST_FAILURE:'POST_USER_USER_LIST_FAILURE',
    POST_USER_USER_LIST_FAILURE_INVALID:'POST_USER_USER_LIST_FAILURE_INVALID',

    GET_EVENT_LISTING_REQUEST:'GET_EVENT_LISTING_REQUEST',
    GET_EVENT_LISTING_SUCCESS:'GET_EVENT_LISTING_SUCCESS',
    GET_EVENT_LISTING_FAILURE:'GET_EVENT_LISTING_FAILURE',
    GET_EVENT_LISTING_FAILURE_INVALID:'GET_EVENT_LISTING_FAILURE_INVALID',

    POST_SET_MPIN_REQUEST:'POST_SET_MPIN_REQUEST',
    POST_SET_MPIN_SUCCESS:'POST_SET_MPIN_SUCCESS',
    POST_SET_MPIN_FAILURE:'POST_SET_MPIN_FAILURE',
    POST_SET_MPIN_FAILURE_INVALID:'POST_SET_MPIN_FAILURE_INVALID',
    
    
    GET_EVENT_DESCRIPTION_REQUEST:'GET_EVENT_DESCRIPTION_REQUEST',
    GET_EVENT_DESCRIPTION_SUCCESS:'GET_EVENT_DESCRIPTION_SUCCESS',
    GET_EVENT_DESCRIPTION_FAILURE:'GET_EVENT_DESCRIPTION_FAILURE',
    GET_EVENT_DESCRIPTION_FAILURE_INVALID:'GET_EVENT_DESCRIPTION_FAILURE_INVALID',


    GET_EVENT_LISTING_CLEAR_DATA:'GET_EVENT_LISTING_CLEAR_DATA',
    CLEAR_LOGIN_FIELDS:'CLEAR_LOGIN_FIELDS',

    ADD_LOCATION : 'ADD_LOCATION',
    SET_USER_LOCATIONS : 'SET_USER_LOCATIONS',

        } 
